data:
  exp: 'exp9'
  model_name: 'MPI-ESM1-2-LR'
  raw_path: 'MPI-ESM1-2-LR/r1-r50i1p1f1/'
  dataset_path: 'MPI-ESM1-2-LR/annual/'
  seed_subsets: 42
  nb_member_per_subsets: 30 # one-to-many approach. If n = 1, individual approach.
  one_to_many: True
  nb_subsets: 1  # only if one-to-many is True
  piControl_diff: True
  predict_only_last_timestep: True
  timescale: 'annual'
  seq_length: 5
  moving_window: 1


train: # for training
  val_size: 0.2 # in case simus_val is None
  seed: 42
  arch: 'time-unet'
  learning_rate: 0.0001
  max_epochs: 100
  batch_size: 8
  runs_dir: 'MPI-ESM1-2-LR/annual/exp9/'
  inputs: ['CO2', 'SO2', 'CH4', 'BC', 'tau']
  outputs: ['pr']
  simus_train: ['historical', 'hist-nat', 'hist-aer', 'hist-GHG', 'ssp119', 'ssp126', 'ssp585']
  simus_val: ['ssp370']
  simus_test: ['ssp245']
  simus_inference: ['ssp245']
  img_size: [96, 192]
  scheduler_step_size: 50
  scheduler_gamma: 0.1
  lstm_units: 64
  monitor_metric: 'val_nrmse' # for best checkpointing and hyperparameter optimization
  early_stopping: 20