tas:
  shortname: tas
  longname: Temperature
  unit: K
  lim:
    values: [-12, 12] # if climatology
    rmse: [0, 1.75]
    mae: [0, 1.5]
    temporal_correlation: [-1, 1]
    mean_error: [-0.9, 0.9]
  color: 'red'
  cmap:
    values: 'coolwarm'
    rmse: 'viridis'
    mae: 'viridis'
    temporal_correlation: 'coolwarm'
    mean_error: 'coolwarm'
    std: 'Reds'
    

pr:
  shortname: pr
  longname: Precipitation
  unit: mm/day
  lim:
    values: [-4, 4] 
    rmse: [0, 3]
    mae: [0, 2.5]
    temporal_correlation: [-1, 1]
    mean_error: [-0.6, 0.6]
  color: 'c'
  cmap:
    values: 'BrBG'
    rmse: 'viridis'
    mae: 'viridis'
    temporal_correlation: 'coolwarm'
    mean_error: 'coolwarm'


CO2:
  longname: | 
    Cumulative anthropogenic CO2 
    emissions since 1850
  unit: GtCO2
  lim:
    values: [0, 10000]
  color: 'darkblue'  
      
CH4:
  longname: | 
    Anthropogenic CH4 emissions
  unit: GtCH4 / year
  lim:
    values: [0, 0.8]
  color: 'darkorchid'  
      
SO2:
  longname: | 
    Anthropogenic SO2 
    emissions
  unit: TgSO2 / year
  lim:
    values: [0, 8e-12]
  color: 'violet'  
      
BC: 
  longname: |
    Anthropogenic BC 
    emissions
  unit: TgBC / year 
  lim:
    values: [0, 5e-13]
  color: 'pink'  

historical:
  color: 'k'

ssp119: 
  color: 'orange'

ssp126:
  color: 'green'

ssp245:
  color: 'b'

ssp370:
  color: 'r'

ssp585:
  color: 'mediumorchid'