compare:
  title: 'seq_length'
  runs_to_compare:
    '1':
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed42_seq1_mem30_sub1/lightning_logs/version_0
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed43_seq1_mem30_sub1/lightning_logs/version_0
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed44_seq1_mem30_sub1/lightning_logs/version_0
    '5':
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed42_seq5_mem30_sub1/lightning_logs/version_0
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed43_seq5_mem30_sub1/lightning_logs/version_0
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed44_seq5_mem30_sub1/lightning_logs/version_0
    '10':
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed42_seq10_mem30_sub1/lightning_logs/version_1
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed43_seq10_mem30_sub1/lightning_logs/version_4
      - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed44_seq10_mem30_sub1/lightning_logs/version_0
