# new func to find name of run from params (eviter les répétitions)?
exp: 'exp1'
timescale: 'annual'
model_name: 'MPI-ESM1-2-LR'

compare:
  title: 'nb_member'
  runs_to_compare: # to compare version and cross-validation    

    'ssp126':
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed42_seq5_mem50_sub1/lightning_logs/version_20
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed43_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed44_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed45_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed46_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed47_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed48_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed49_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed50_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp2/pr_cnn-lstm_seed51_seq5_mem50_sub1/lightning_logs/version_0

    'ssp245':
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed42_seq5_mem50_sub1/lightning_logs/version_20
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed43_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed44_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed45_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed46_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed47_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed48_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed49_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed50_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed51_seq5_mem50_sub1/lightning_logs/version_0

      
    'ssp370':
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed42_seq5_mem50_sub1/lightning_logs/version_20
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed43_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed44_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed45_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed46_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed47_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed48_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed49_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed50_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp3/pr_cnn-lstm_seed51_seq5_mem50_sub1/lightning_logs/version_0


    'ssp585':
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed42_seq5_mem50_sub1/lightning_logs/version_22
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed43_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed44_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed45_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed46_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed47_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed48_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed49_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed50_seq5_mem50_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp4/pr_cnn-lstm_seed51_seq5_mem50_sub1/lightning_logs/version_0


  predictions_to_compare: # to compare predictions (seeds mean)

predict:
  'ssp245':
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed42_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed43_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed44_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed45_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed46_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed47_seq10_mem50_sub1/lightning_logs/version_2
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed48_seq10_mem50_sub1/lightning_logs/version_1
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed49_seq10_mem50_sub1/lightning_logs/version_1
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed50_seq10_mem50_sub1/lightning_logs/version_1
  - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed51_seq10_mem50_sub1/lightning_logs/version_1

