compare:
  title: 'nb_member'
  runs_to_compare: # to compare version and cross-validation
    'mem=5':
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed42_seq10_mem5_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed43_seq10_mem5_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed44_seq10_mem5_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed45_seq10_mem5_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed46_seq10_mem5_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed47_seq10_mem5_sub1/lightning_logs/version_0
    'mem=30':
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed42_seq10_mem30_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed43_seq10_mem30_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed44_seq10_mem30_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed45_seq10_mem30_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed46_seq10_mem30_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed47_seq10_mem30_sub1/lightning_logs/version_0
    'mem=50':
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed42_seq10_mem50_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed43_seq10_mem50_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed44_seq10_mem50_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed45_seq10_mem50_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed46_seq10_mem50_sub1/lightning_logs/version_0
        - MPI-ESM1-2-LR/annual/exp1/pr_cnn-lstm_seed47_seq10_mem50_sub1/lightning_logs/version_0

  predictions_to_compare: # to compare predictions (seeds mean)

predict:
  'MPI-ESM1-2-LR_201501-210012_cnn-lstm_seq10_mem30_sub1.nc':
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed42_seq10_mem30_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed43_seq10_mem30_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed44_seq10_mem30_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed45_seq10_mem30_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed46_seq10_mem30_sub1/lightning_logs/version_0
    - MPI-ESM1-2-LR/annual/exp1/cnn-lstm_seed47_seq10_mem30_sub1/lightning_logs/version_0